### ISSUE TITLE
Fehler Log 1.8.0

### ISSUE THREAD

**Issue by cTech1987** [iobroker-community-adapters/ioBroker.info#268]
Der Adapter verursacht folgenden Log:
Hat wer Abhilfe was man tun kann?

host.ioBroker | 2021-04-10 11:59:57.429 | error | instance system.adapter.info.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.ioBroker | 2021-04-10 11:59:57.428 | error | Caught by controller[0]: at processTicksAndRejections (internal/process/task_queues.js:79:11)
host.ioBroker | 2021-04-10 11:59:57.427 | error | Caught by controller[0]: at /opt/iobroker/node_modules/systeminformation/lib/bluetooth.js:98:30
host.ioBroker | 2021-04-10 11:59:57.427 | error | Caught by controller[0]: at Object.getFilesInPath (/opt/iobroker/node_modules/systeminformation/lib/util.js:669:12)
host.ioBroker | 2021-04-10 11:59:57.426 | error | Caught by controller[0]: at getFilesRecursively (/opt/iobroker/node_modules/systeminformation/lib/util.js:661:16)
host.ioBroker | 2021-04-10 11:59:57.426 | error | Caught by controller[0]: at getDirectories (/opt/iobroker/node_modules/systeminformation/lib/util.js:654:12)
host.ioBroker | 2021-04-10 11:59:57.425 | error | Caught by controller[0]: at readdirSync (fs.js:955:3)
host.ioBroker | 2021-04-10 11:59:57.421 | error | Caught by controller[0]: Error: EACCES: permission denied, scandir '/var/lib/bluetooth/'
info.0 | 2021-04-10 11:59:56.356 | warn | (11730) State "info.0.sysinfo.disks.diskLayout.dev0.name" has no existing object, this might lead to an error in future versions
info.0 | 2021-04-10 11:59:55.906 | warn | (11730) Terminated (UNCAUGHT_EXCEPTION): Without reason
node-red.0 | 2021-04-10 11:59:55.312 | info | (11818) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
info.0 | 2021-04-10 11:59:54.324 | error | (11730) Exception-Code: EACCES: EACCES: permission denied, scandir '/var/lib/bluetooth/'
info.0 | 2021-04-10 11:59:54.323 | error | at processTicksAndRejections (internal/process/task_queues.js:79:11)
info.0 | 2021-04-10 11:59:54.323 | error | at /opt/iobroker/node_modules/systeminformation/lib/bluetooth.js:98:30
info.0 | 2021-04-10 11:59:54.323 | error | at Object.getFilesInPath (/opt/iobroker/node_modules/systeminformation/lib/util.js:669:12)
info.0 | 2021-04-10 11:59:54.323 | error | at getFilesRecursively (/opt/iobroker/node_modules/systeminformation/lib/util.js:661:16)
info.0 | 2021-04-10 11:59:54.323 | error | at getDirectories (/opt/iobroker/node_modules/systeminformation/lib/util.js:654:12)
info.0 | 2021-04-10 11:59:54.323 | error | at readdirSync (fs.js:955:3)
info.0 | 2021-04-10 11:59:54.323 | error | (11730) Error: EACCES: permission denied, scandir '/var/lib/bluetooth/'
info.0 | 2021-04-10 11:59:54.319 | error | (11730) uncaught exception: EACCES: permission denied, scandir '/var/lib/bluetooth/'

**Comment by vaaarg** [comment]
`
<html>
<body>


host.piblack | 2021-06-25 06:46:16.205 | info | Restart adapter system.adapter.info.0 because enabled
-- | -- | -- | --
host.piblack | 2021-06-25 06:46:16.204 | error | instance system.adapter.info.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.piblack | 2021-06-25 06:46:16.204 | error | Caught by controller[0]: at processTicksAndRejections (internal/process/task_queues.js:77:11)
host.piblack | 2021-06-25 06:46:16.204 | error | Caught by controller[0]: at /opt/iobroker/node_modules/systeminformation/lib/bluetooth.js:98:30
host.piblack | 2021-06-25 06:46:16.203 | error | Caught by controller[0]: at Object.getFilesInPath (/opt/iobroker/node_modules/systeminformation/lib/util.js:695:12)
host.piblack | 2021-06-25 06:46:16.203 | error | Caught by controller[0]: at getFilesRecursively (/opt/iobroker/node_modules/systeminformation/lib/util.js:687:16)
host.piblack | 2021-06-25 06:46:16.203 | error | Caught by controller[0]: at getDirectories (/opt/iobroker/node_modules/systeminformation/lib/util.js:680:12)
host.piblack | 2021-06-25 06:46:16.202 | error | Caught by controller[0]: at readdirSync (fs.js:1043:3)
host.piblack | 2021-06-25 06:46:16.202 | error | Caught by controller[0]: Error: EACCES: permission denied, scandir '/var/lib/bluetooth/'
info.0 | 2021-06-25 06:46:15.433 | warn | (2137) Terminated (UNCAUGHT_EXCEPTION): Without reason
info.0 | 2021-06-25 06:46:15.431 | info | (2137) terminating
info.0 | 2021-06-25 06:46:15.430 | info | (2137) cleaned everything up...
info.0 | 2021-06-25 06:46:15.205 | error | (2137) Exception-Code: EACCES: EACCES: permission denied, scandir '/var/lib/bluetooth/'
info.0 | 2021-06-25 06:46:15.204 | error | (2137) Error: EACCES: permission denied, scandir '/var/lib/bluetooth/' at readdirSync (fs.js:1043:3) at getDirectories (/opt/iobroker/node_modules/systeminformation/lib/util.js:680:12) at
info.0 | 2021-06-25 06:46:15.203 | error | (2137) uncaught exception: EACCES: permission denied, scandir '/var/lib/bluetooth/'
info.0 | 2021-06-25 06:46:14.205 | info | (2137) Reading/updating systemdata.
info.0 | 2021-06-25 06:46:14.146 | info | (2137) starting. Version 1.8.0 in /opt/iobroker/node_modules/iobroker.info, node: v14.17.1, js-controller: 3.2.16


</body>
</html>`

**Comment by vaaarg** [comment]
same here

`
<html>
<body>


host.piblack | 2021-06-25 06:46:16.205 | info | Restart adapter system.adapter.info.0 because enabled
-- | -- | -- | --
host.piblack | 2021-06-25 06:46:16.204 | error | instance system.adapter.info.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.piblack | 2021-06-25 06:46:16.204 | error | Caught by controller[0]: at processTicksAndRejections (internal/process/task_queues.js:77:11)
host.piblack | 2021-06-25 06:46:16.204 | error | Caught by controller[0]: at /opt/iobroker/node_modules/systeminformation/lib/bluetooth.js:98:30
host.piblack | 2021-06-25 06:46:16.203 | error | Caught by controller[0]: at Object.getFilesInPath (/opt/iobroker/node_modules/systeminformation/lib/util.js:695:12)
host.piblack | 2021-06-25 06:46:16.203 | error | Caught by controller[0]: at getFilesRecursively (/opt/iobroker/node_modules/systeminformation/lib/util.js:687:16)
host.piblack | 2021-06-25 06:46:16.203 | error | Caught by controller[0]: at getDirectories (/opt/iobroker/node_modules/systeminformation/lib/util.js:680:12)
host.piblack | 2021-06-25 06:46:16.202 | error | Caught by controller[0]: at readdirSync (fs.js:1043:3)
host.piblack | 2021-06-25 06:46:16.202 | error | Caught by controller[0]: Error: EACCES: permission denied, scandir '/var/lib/bluetooth/'
info.0 | 2021-06-25 06:46:15.433 | warn | (2137) Terminated (UNCAUGHT_EXCEPTION): Without reason
info.0 | 2021-06-25 06:46:15.431 | info | (2137) terminating
info.0 | 2021-06-25 06:46:15.430 | info | (2137) cleaned everything up...
info.0 | 2021-06-25 06:46:15.205 | error | (2137) Exception-Code: EACCES: EACCES: permission denied, scandir '/var/lib/bluetooth/'
info.0 | 2021-06-25 06:46:15.204 | error | (2137) Error: EACCES: permission denied, scandir '/var/lib/bluetooth/' at readdirSync (fs.js:1043:3) at getDirectories (/opt/iobroker/node_modules/systeminformation/lib/util.js:680:12) at
info.0 | 2021-06-25 06:46:15.203 | error | (2137) uncaught exception: EACCES: permission denied, scandir '/var/lib/bluetooth/'
info.0 | 2021-06-25 06:46:14.205 | info | (2137) Reading/updating systemdata.
info.0 | 2021-06-25 06:46:14.146 | info | (2137) starting. Version 1.8.0 in /opt/iobroker/node_modules/iobroker.info, node: v14.17.1, js-controller: 3.2.16


</body>
</html>`

**Comment by Apollon77** [comment]
Please try with Github version
