### ISSUE TITLE
Log-Eintrag mit js-Controller 3.3.1

### ISSUE THREAD

**Issue by darkman242** [iobroker-community-adapters/ioBroker.info#269]
Nach Update des js-Controllers wird nachfolgendes im Log angezeigt.

`
info.0 | 2021-04-30 07:34:56.392 | warn | State value to set for "info.0.sysinfo.disks.fsSize.fs0.used_hist" has wrong type "string" but has to be "array"
-- | -- | -- | --
`

**Comment by Grothesk242** [comment]
Ich werfe noch ein paar dazu: 

```
2021-04-30 14:40:24.709  - warn: info.0 (847) State value to set for "info.0.sysinfo.cpu.info.cache-l1d" has wrong type "string" but has to be "number"
2021-04-30 14:40:24.710  - warn: info.0 (847) State value to set for "info.0.sysinfo.cpu.info.cache-l1i" has wrong type "string" but has to be "number"
2021-04-30 14:40:24.711  - warn: info.0 (847) State value to set for "info.0.sysinfo.cpu.info.cache-l2" has wrong type "string" but has to be "number"
2021-04-30 14:40:24.712  - warn: info.0 (847) State value to set for "info.0.sysinfo.cpu.info.cache-l3" has wrong type "string" but has to be "number"
```

**Comment by daniel-lo** [comment]
Bei mir so:


  |   |   |  
-- | -- | -- | --
info.0 | 2021-04-30 18:32:49.586 | warn | (12249) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 18:32:49.132 | warn | (12249) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 18:32:46.643 | warn | (12249) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 18:32:46.131 | warn | (12249) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 18:32:43.646 | warn | (12249) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 18:32:43.132 | warn | (12249) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 18:32:40.581 | warn | (12249) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 18:32:40.128 | warn | (12249) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 18:32:37.580 | warn | (12249) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 18:32:37.133 | warn | (12249) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 18:32:34.582 | warn | (12249) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 18:32:34.131 | warn | (12249) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 18:32:31.582 | warn | (12249) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 18:32:31.127 | warn | (12249) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 18:32:28.581 | warn | (12249) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 18:32:28.127 | warn | (12249) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 18:32:25.582 | warn | (12249) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 18:32:25.127 | warn | (12249) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 18:32:22.584 | warn | (12249) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 18:32:22.125 | warn | (12249) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
info.0 | 2021-04-30 18:32:19.706 | warn | (12249) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"

**Comment by msiemers** [comment]
Hier die selben Meldungen unter 3.3.2

**Comment by daniel-lo** [comment]
Hab mal alle Objekte gelöscht und den Adapter neu gestartet .. hilft aber auch nicht. Das hier ist mir neu aufgefallen .. war aber vielleicht schon vorher da:

  | (8475) State "info.0.sysinfo.memory.info.cached" has no existing object, this might lead to an error in future versions
-- | --

**Comment by WolfgangGr** [comment]
**Describe the bug**  
After updating of js-controller 3.2.16 to 3.3.2 it will be logged a warning
`2021-04-30 20:52:37.800 - warn: info.0 (6007) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"`

**To Reproduce**  
Steps to reproduce the behavior:
Update to js-controller 3.3.2

**Expected behavior**  
no warning

**Screenshots & Logfiles**  
`2021-04-30 20:52:37.800 - warn: info.0 (6007) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
2021-04-30 20:52:38.022 - warn: info.0 (6007) State value to set for "info.0.sysinfo.cpu.info.cache-l1d" has wrong type "string" but has to be "number"
2021-04-30 20:52:38.027 - warn: info.0 (6007) State value to set for "info.0.sysinfo.cpu.info.cache-l1i" has wrong type "string" but has to be "number"
2021-04-30 20:52:38.029 - warn: info.0 (6007) State value to set for "info.0.sysinfo.cpu.info.cache-l2" has wrong type "string" but has to be "number"
2021-04-30 20:52:38.271 - warn: info.0 (6007) State value to set for "info.0.sysinfo.cpu.info.cache-l3" has wrong type "string" but has to be "number"
2021-04-30 20:52:38.461 - warn: info.0 (6007) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"`

**Versions:**  
 - Adapter version: <1.7.15>
 - JS-Controller version: <3.3.2>
 - Node version: <12.22.1>
 - Operating system: <Raspian buster 10>

**Comment by arteck** [comment]
![grafik](https://user-images.githubusercontent.com/6681528/120061919-be2d5480-c05f-11eb-9f30-8c7576b23692.png)

**Comment by Apollon77** [comment]
Please try with GitHub version.
